force-app/main/default/objects/Assessment_Template__c/Assessment_Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Conditional_Response__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Response__c</fullName>
    <label>Conditional Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/HelpText__c.field-meta.xml
<CustomField>
    <fullName>HelpText__c</fullName>
    <label>HelpText</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/OptionValueSet__c.field-meta.xml
<CustomField>
    <fullName>OptionValueSet__c</fullName>
    <label>Response Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence_Number__c</fullName>
    <label>Question Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Requires_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>Requires_File_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires File Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Section_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Section_Sequence_Number__c</fullName>
    <label>Section Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SectionSelector.cls
/** 
* Class Name        : SectionSelector
* Developer         : Sai Koushik Nimmaturi and Reethika Velpula        
* Created Date      : 
* @description       : SectionSelector contains queries related to Section Object.
* Last Modified Date: 
*/
public with sharing class SectionSelector {
    public static SecurityCheckController safe = new SecurityCheckController();//use singleton pattern
    

    private static SectionSelector selector = null; //private static instance of the class
    
    /**
    * @description Singleton Design Pattern 
    * @return
    */
    public static SectionSelector getInstance(){
           if(selector == null){
                selector = new SectionSelector();
            }
        return selector;
    }
    /**
    * @description To get all the sections related to a template.
    * @param templateId This is a record id of an Template.
    * @return 
    */
    public List<Section__c> getSectionsforTemplate(string templateId){
        string query = 'SELECT Id,Name,Assessment_Template__c,Section_Sequence_Number__c,'
                    +  '(SELECT Id,Name,Question__c,Assessment_Template__c,Question_Type__c,'
                    +  'Conditional_Response__c,HelpText__c,OptionValueSet__c,Parent_Question__c,'
                    +  'Question_Sequence_Number__c,Required__c,Requires_File_Upload__c,Section__c'
                    + ' FROM Questions__r WHERE Parent_Question__c = null ORDER BY CreatedDate ASC)'
                    + ' FROM Section__c'
                    + ' WHERE Assessment_Template__c=\'' + String.escapeSingleQuotes(templateId) + '\''
                    + ' WITH SECURITY_ENFORCED';
        List<Section__c>  sectionsList = safe.doQuery(query);
        return sectionsList;
    }

   /**
    * @description To get sections related to template.
    * @param templateId It is template id.
    * @param sectionName Name of the section.
    * @return
    */
    public List<Sobject> getSections(String templateId, String sectionName){
        sectionName = '\'%'+sectionName+'%\'';
        try{
            String query =  'SELECT Id,Name,Assessment_Template__c'
                            + ' FROM section__c'
                            + ' WHERE Assessment_Template__c=\'' + templateId + '\''
                            + ' AND Name LIKE ' + sectionName
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY CreatedDate DESC';
            return safe.doQuery(query);
        }catch(Exception e){
            String errorMsg = e.getMessage();
            throw new AuraHandledException(errorMsg);
        }
    }
}