force-app/main/default/objects/Assessment_Template__c/Assessment_Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorTransactionLog__c/ErrorTransactionLog__c.object-meta.xml
<CustomObject>
    <label>ErrorTransactionLog</label>
    <nameField>
        <label>ErrorTransactionLog Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ErrorTransactionLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ErrorTransactionLog__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ErrorTransactionLog__c/fields/Error_Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Error_Stack_Trace__c</fullName>
    <label>Error Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ErrorTransactionLog__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Conditional_Response__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Response__c</fullName>
    <label>Conditional Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/HelpText__c.field-meta.xml
<CustomField>
    <fullName>HelpText__c</fullName>
    <label>HelpText</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/OptionValueSet__c.field-meta.xml
<CustomField>
    <fullName>OptionValueSet__c</fullName>
    <label>Response Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence_Number__c</fullName>
    <label>Question Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Requires_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>Requires_File_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires File Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/SectionName__c.field-meta.xml
<CustomField>
    <fullName>SectionName__c</fullName>
    <formula>Section__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SectionName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuestionSelector.cls
/** 
* Class Name        : QuestionSelector
* Developer         : Sai Koushik Nimmaturi,Reethika Velpula, Sri Kushal Reddy N        
* Created Date      : 
* @description      : QuestionSelector contains queries related to Question Object.
* Last Modified Date: 
*/
public with sharing class QuestionSelector {
    public static SecurityCheckController safe = new SecurityCheckController();   //Implementing singleton pattern
    public static List<ErrorTransactionLog__c> errorList;   //Stores list of ErrorTransactionLog__c records to store errors
    public static ErrorTransactionLog__c errorRec;   //Used for creating an instance for ErrorTransactionLog__c to log/store an error
    
    /**
    * @description To get all the sections related to a template.
    * @param templateId This is a record id of an Template.
    * @return 
    */
    public List<Question__c> getSubQuestions(set<Id> mqIds){
        string query = 'SELECT Id,Name,Question__c,Assessment_Template__c,'
                    +  'Question_Type__c,Conditional_Response__c,HelpText__c,OptionValueSet__c,'
                    +  'Parent_Question__c,Question_Sequence_Number__c,Required__c,'
                    +  'Requires_File_Upload__c,Section__c'
                    + ' FROM Question__c'
                    + ' WHERE Parent_Question__c != null'
                    + ' AND Parent_Question__c IN:mqIds'
                    + ' ORDER BY CreatedDate ASC';
        Map<String, Object> bindVariables = new Map<String, Object>{'mqIds' => mqIds};
        List<Question__c>  questionList = safe.doQueryWithBinds(query,bindVariables);
        return questionList;
    }

    /**
    * @description Fetches the Question__c records w.r.t fields, filter, child queries, etc.
    * @param parameterMap It is a Map of all parameters like fields, filter, child queries, etc.
    * @return Map of Id and its Question__c record
    */
    Public Static List<Question__c> fetchQuestions(Map<String,Object> parameterMap) {
        List<String> fields = (List<String>)JSON.deserialize(JSON.serialize(parameterMap.get('fields')), List<String>.class);
        String filter = (String)parameterMap.get('filter');
        if(fields != null && !fields.isEmpty()) {
            filter = (filter == null)?'':filter;
            String query = 'SELECT ' + String.join(fields,',') + ' FROM Question__c ' + filter;
            try {
                List<Question__c> qList = safe.doQuery(query);
        		return qList;
            }
            catch(Exception e) {
                /*errorList = new List<ErrorTransactionLog__c>();
            	errorRec = new ErrorTransactionLog__c();
                errorRec.Class_Name__c = 'ContentVersionSelector';
                errorRec.Error_Stack_Trace__c = e.getStackTraceString();
                errorRec.Name = 'Error while fetching ContentVersion records';
                errorRec.LWC_Component_Name__c = '';
                errorRec.Method_Name__c = 'fetchContentVersions';
                errorList.add(errorRec);
                Database.SaveResult[] results = Database.insert(errorList, false);*/
                throw new AuraHandledException(e.getMessage());   //Throws an exception
            }
        }
        return null;
    }
    
    /**
    * @description Updates the Child Questions with updated Sequence and fetches the questions with updated sequence
    * @param parameterMap It is a Map of all parameters like Questions Ids to be updated
    * @return List of Question__c records
    */
    Public Static List<Question__c> updateQuestionsSequence(Map<String,Object> parameterMap)
    {
        List<String> questionIdList = (List<Id>)JSON.deserialize(JSON.serialize(parameterMap.get('questionIdList')),List<String>.class);
        String questionId = (String)parameterMap.get('questionId');
        if(!questionIdList.isEmpty() && questionIdList.size()>0 && questionId!=null && String.isNotBlank(questionId))
        {
            Integer sequenceNo = 1;
            List<Question__c> questionList = new List<Question__c>();
            for(Id question:questionIdList)
            {
                questionList.add(new Question__c(Id=question,Question_Sequence_Number__c=sequenceNo));
                sequenceNo++;
            }
            try
            {
                update questionList;
                List<Question__c> qList = [SELECT Id, Question__c, Conditional_Response__c, Question_Sequence_Number__c FROM Question__c WHERE Parent_Question__c = :String.escapeSingleQuotes(questionId) WITH SECURITY_ENFORCED ORDER BY Question_Sequence_Number__c ASC];
                return qList;
            }
            catch(Exception e)
            {}
        }
        return null;
    }
    /**
    * @description gets all questions data of particular template.
    * @param templateId It is an id of Template
    * @return List of Question__c records
    */
    Public Static List<SObject> getQuestions(String templateId)
    {
         try{
            /*String query =  'SELECT id,name,Section__c,Section__r.Name,Assessment_Template__c,SectionName__c,Question__c,Question_Sequence_Number__c,Question_Type__c,OptionValueSet__c,Parent_Question__c,Conditional_Response__c'
                            + ' FROM Question__c'
                            + ' WHERE Assessment_Template__c=\'' + String.escapeSingleQuotes(templateId) + '\''
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY Question_Sequence_Number__c';*/
            List<SObject> questionslst =[SELECT id,name,Section__c,Section__r.Name,SectionName__c, Question__c,Assessment_Template__c,
                                        Question_Sequence_Number__c,Question_Type__c,OptionValueSet__c,Parent_Question__c,Conditional_Response__c FROM 
                                 		Question__c WHERE Assessment_Template__c =:templateId 
                                        WITH SECURITY_ENFORCED ORDER BY Question_Sequence_Number__c];
            //return safe.doQuery(query);
            return questionslst;
        }
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
        /*List<SObject> questionslst =[SELECT id,name,Section__c,Section__r.Name,SectionName__c, Question__c,Question_Type__c,OptionValueSet__c FROM 
                                 Question__c WHERE Assessment_Template__c =:templateId];
        return questionslst;*/
    }
    /**
    * @description gets question data of particular question.
    * @param templateId it is an id of Template
    * @param questionId it is an id of Question
    * @return List of Question__c record
    */
    Public Static List<SObject> getQuestionsData(String questionId, String templateId)
    {
        try{
            /*String query =  'SELECT id,name,Section__c,Section__r.Name,SectionName__c,HelpText__c,Requires_File_Upload__c,Required__c,Question__c,Question_Type__c,OptionValueSet__c'
                            + ' FROM Question__c'
                            + ' WHERE id=\'' + String.escapeSingleQuotes(questionId) + '\''
                			+ ' AND Assessment_Template__c=\'' + String.escapeSingleQuotes(templateId) +'\''
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY CreatedDate Desc';*/
            System.debug('questionId'+questionId);
            System.debug('templateId'+templateId);
            List<SObject> questionslst =[SELECT id,name,Section__c,Section__r.Name,SectionName__c,HelpText__c,Requires_File_Upload__c,Required__c,
                                     	 Question__c,Question_Type__c,OptionValueSet__c FROM 
                                 	 	 Question__c WHERE id=:questionId AND Assessment_Template__c =:templateId WITH SECURITY_ENFORCED
                                     	 ORDER BY CreatedDate Desc ];
            System.debug('questionslst'+questionslst);
           // return safe.doQuery(query);
           return questionslst;
        }
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
    /**
    * @description gets conditional questions data of particular question.
    * @param templateId it is an id of Template
    * @param questionId it is an id of Question
    * @return List of Question__c record
    */
    Public Static List<SObject> getChildQuestions(String questionId,String templateId)
    {
        try{
            List<SObject> query =  [SELECT id,Name,Question__c,Section__c,Parent_Question__c,Assessment_Template__c
                                    FROM Question__c
                            		WHERE Parent_Question__c =:questionId AND Assessment_Template__c =:templateId
                                    WITH SECURITY_ENFORCED];
            //return safe.doQuery(query);
            return query;
        }
        catch(Exception e)
        {
            throw new AuraHandledException(e.getMessage());
        }
    }
}