force-app/main/default/objects/Assessment_Template__c/Assessment_Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Conditional_Response__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Response__c</fullName>
    <label>Conditional Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/HelpText__c.field-meta.xml
<CustomField>
    <fullName>HelpText__c</fullName>
    <label>HelpText</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/OptionValueSet__c.field-meta.xml
<CustomField>
    <fullName>OptionValueSet__c</fullName>
    <label>Response Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence_Number__c</fullName>
    <label>Question Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Requires_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>Requires_File_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires File Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/SectionName__c.field-meta.xml
<CustomField>
    <fullName>SectionName__c</fullName>
    <formula>Section__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SectionName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Response_Attribute__c/Response_Attribute__c.object-meta.xml
<CustomObject>
    <label>Response Attribute</label>
    <nameField>
        <label>Response Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Response Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Attribute__c/fields/preferred_Not_preferred__c.field-meta.xml
<CustomField>
    <fullName>preferred_Not_preferred__c</fullName>
    <label>preferred/Not preferred</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Non Preferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response_Attribute__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <label>QuestionId</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Response Attributes</relationshipLabel>
    <relationshipName>Response_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Response_Attribute__c/fields/Response_value__c.field-meta.xml
<CustomField>
    <fullName>Response_value__c</fullName>
    <label>Response value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Response_Attribute__c/fields/Upload_Required__c.field-meta.xml
<CustomField>
    <fullName>Upload_Required__c</fullName>
    <label>Upload Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Optional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Response_Question_Map__c/Response_Question_Map__c.object-meta.xml
<CustomObject>
    <label>Response Question Map</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Response Question Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Question Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Question_Map__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuestionId</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Response Question Maps</relationshipLabel>
    <relationshipName>Response_Question_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Question_Map__c/fields/ResponseAttributeId__c.field-meta.xml
<CustomField>
    <fullName>ResponseAttributeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ResponseAttributeId</label>
    <referenceTo>Response_Attribute__c</referenceTo>
    <relationshipLabel>Response Question Maps</relationshipLabel>
    <relationshipName>Response_Question_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuestionAttributeResponseSelector.cls
public class QuestionAttributeResponseSelector {
	public static SecurityCheckController safe = new SecurityCheckController();
    private static Savepoint sp;
    @AuraEnabled
    public static List<Sobject> getSections(String templateId, String sectionName)
    {
        sectionName = '\'%'+sectionName+'%\'';
        System.debug('templateId : '+templateId +'  sectionName : '+sectionName);
        try{
            String query =  'SELECT Id,Name,Assessment_Template__c'
                            + ' FROM section__c'
                            + ' WHERE Assessment_Template__c=\'' + templateId + '\''
                			+ ' AND Name LIKE ' + sectionName
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY CreatedDate Desc';
            return safe.doQuery(query);
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
        /*List<Sobject> sections = [SELECT id,name,Assessment_Template__c FROM section__c WHERE  Assessment_Template__c =:templateId
                                  AND name LIKE :sectionName];
        
        return sections;*/
    }
    @AuraEnabled
    public static List<SObject> getQuestions(String templateId)
    {
         try{
            String query =  'SELECT id,name,Section__c,Section__r.Name,Assessment_Template__c,SectionName__c,Question__c,Question_Sequence_Number__c,Question_Type__c,OptionValueSet__c,Parent_Question__c,Conditional_Response__c'
                            + ' FROM Question__c'
                            + ' WHERE Assessment_Template__c=\'' + String.escapeSingleQuotes(templateId) + '\''
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY Question_Sequence_Number__c';
            return safe.doQuery(query);
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
        /*List<SObject> questionslst =[SELECT id,name,Section__c,Section__r.Name,SectionName__c, Question__c,Question_Type__c,OptionValueSet__c FROM 
                                 Question__c WHERE Assessment_Template__c =:templateId];
        return questionslst;*/
    }
    @AuraEnabled
    public static List<SObject> getQuestionsData(String questionId, String templateId)
    {
        try{
            String query =  'SELECT id,name,Section__c,Section__r.Name,SectionName__c,HelpText__c,Requires_File_Upload__c,Required__c,Question__c,Question_Type__c,OptionValueSet__c'
                            + ' FROM Question__c'
                            + ' WHERE id=\'' + String.escapeSingleQuotes(questionId) + '\''
                			+ ' AND Assessment_Template__c=\'' + String.escapeSingleQuotes(templateId) +'\''
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY CreatedDate Desc';
            return safe.doQuery(query);
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
        /*List<SObject> questionslst =[SELECT id,name,Section__c,Section__r.Name,SectionName__c,HelpText__c,Requires_File_Upload__c,Required__c,
                                     Question__c,Question_Type__c,OptionValueSet__c FROM 
                                 	 Question__c WHERE id=:questionId AND Assessment_Template__c =:templateId];
        return questionslst;*/
    }
    @AuraEnabled
    public static List<SObject> getResponseAttributes(String questionId)
    {
        System.debug('questionId'+questionId);
         try{
            String query =  'SELECT id,name,Response_value__c,Score__c,Upload_Required__c,preferred_Not_preferred__c,Weight__c'
                            + ' FROM Response_Attribute__c'
                            + ' WHERE QuestionId__c=\'' + String.escapeSingleQuotes(questionId) + '\''
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY CreatedDate Desc';
             System.debug(safe.doQuery(query));
            return safe.doQuery(query);
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
        /*List<SObject> questionslst =[SELECT id,name,Response_value__c,Score__c,Upload_Required__c,preferred_Not_preferred__c,Weight__c FROM 
                                 	 Response_Attribute__c WHERE QuestionId__c=:questionId ];
        return questionslst;*/
    }
    @AuraEnabled
    public static List<SObject> getQuestionResponseAttribute(String responseId)
    {
         try{
            String query =  'SELECT id,name,Response_value__c,Score__c,Upload_Required__c,preferred_Not_preferred__c,Weight__c'
                            + ' FROM Response_Attribute__c'
                            + ' WHERE Id=\'' + String.escapeSingleQuotes(responseId) + '\''
                            + ' WITH SECURITY_ENFORCED'
                            + ' ORDER BY CreatedDate Desc';
            return safe.doQuery(query);
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
    }
    @AuraEnabled
    public static List<SObject> getQuestionResponseMap(List<String> quesId)
    {
        try{
            List<SObject> query =  [SELECT id,Name,QuestionId__c,ResponseAttributeId__c 
                                    FROM Response_Question_Map__c
                            		WHERE QuestionId__c IN:quesId 
                                    WITH SECURITY_ENFORCED];
            //return safe.doQuery(query);
            return query;
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
    }
    @AuraEnabled
    public static List<SObject> getQuesRespAttribute(List<String> respAttrId)
    {
        try{
            List<SObject> query =  [SELECT id,Name,Response_value__c,QuestionId__c,preferred_Not_preferred__c,Score__c,
                                    Upload_Required__c,Weight__c
                                    FROM Response_Attribute__c
                            		WHERE Id IN:respAttrId 
                                    WITH SECURITY_ENFORCED];
            //return safe.doQuery(query);
            return query;
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
    }
    @AuraEnabled
        public static List<SObject> getChildQuestions(String questionId,String templateId)
    {
        try{
            List<SObject> query =  [SELECT id,Name,Question__c,Section__c,Parent_Question__c,Assessment_Template__c
                                    FROM Question__c
                            		WHERE Parent_Question__c =:questionId AND Assessment_Template__c =:templateId
                                    WITH SECURITY_ENFORCED];
            //return safe.doQuery(query);
            return query;
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
    }
    @AuraEnabled
    public static List<SObject> getQuestionRespAttributes(List<String> questionlst)
    {
        try{
            List<SObject> query =  [SELECT id,Name,Response_value__c,QuestionId__c,preferred_Not_preferred__c,Score__c,
                                    Upload_Required__c,Weight__c
                                    FROM Response_Attribute__c
                            		WHERE QuestionId__c IN:questionlst 
                                    WITH SECURITY_ENFORCED];
            //return safe.doQuery(query);
            System.debug(query);
            return query;
            
        }
        catch(Exception e)
        {
            String errorMsg = e.getMessage();
            System.debug('errorMsg'+errorMsg);
            throw new AuraHandledException(errorMsg);
        }
    }

    @AuraEnabled
    public static List<Response_Attribute__c> getRespAttforQuestion(Map<Id,Id> questionIdsMap){
        List<Response_Attribute__c> resAttList = [SELECT Id,QuestionId__c,Name,
                                    preferred_Not_preferred__c,Response_value__c,
                                    Score__c,Upload_Required__c,Weight__c
                                    FROM Response_Attribute__c
                                    WHERE QuestionId__c IN:questionIdsMap.keySet()
                                    WITH SECURITY_ENFORCED];
        return resAttList;
    }
}