force-app/main/default/objects/Assessment_Template__c/Assessment_Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Inactive&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Template_Version__c/Assessment_Template_Version__c.object-meta.xml
<CustomObject>
    <label>Assessment Template Version</label>
    <nameField>
        <label>Assessment Template Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Template Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Template_Version__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Assessment Template Versions</relationshipLabel>
    <relationshipName>Assessment_Template_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Assessment_Template_Version__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template Version</label>
    <referenceTo>Assessment_Template_Version__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Conditional_Response__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Response__c</fullName>
    <label>Conditional Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/HelpText__c.field-meta.xml
<CustomField>
    <fullName>HelpText__c</fullName>
    <label>HelpText</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/OptionValueSet__c.field-meta.xml
<CustomField>
    <fullName>OptionValueSet__c</fullName>
    <label>Response Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence_Number__c</fullName>
    <label>Question Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Requires_File_Upload__c.field-meta.xml
<CustomField>
    <fullName>Requires_File_Upload__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires File Upload</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Assessment_Template_Version__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template Version</label>
    <referenceTo>Assessment_Template_Version__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Cloned_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Cloned_Record_Id__c</fullName>
    <label>Cloned Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TemplateController.cls
public class TemplateController {

    @AuraEnabled
    public static ResultWrapper createTemplateVersion(string recordId){
        ResultWrapper resultWrap = new ResultWrapper();
        Savepoint sp = Database.setSavepoint();
        try{
            List<Section__c> newSectionsList = new List<Section__c>();
            List<Assessment_Template_Version__c> latestAssVerList = [SELECT Id,Name,Assessment_Template__c FROM Assessment_Template_Version__c WHERE Assessment_Template__c=:recordId ORDER BY CreatedDate];
            Integer versionCount = latestAssVerList.size();      
            if(latestAssVerList.isEmpty() == false){
                string versionId = '';
                string newVersionId = '';
                List<Assessment_Template_Version__c> versionList = new List<Assessment_Template_Version__c>();

                set<Id> existingVerIds = new set<Id>();
                Assessment_Template_Version__c activeVer = latestAssVerList[0];
                activeVer.Status__c = 'Inactive';
                versionList.add(activeVer);
                
                Assessment_Template_Version__c newVer = activeVer.clone(false, true); //do a deep clone
                newVer.Name = 'Version '+string.valueOf(versionCount+1);
                newVer.Status__c = 'Inactive';
                versionList.add(newVer);
                
                for(Assessment_Template_Version__c tempVer:versionList){
                    if(tempVer.Id != null){
                        existingVerIds.add(tempVer.Id);
                    }
                }
                upsert versionList;
                
                for(Assessment_Template_Version__c tempVer:versionList){
                    if(existingVerIds.contains(tempVer.Id)){
                        versionId = tempVer.Id;
                    }else{
                        newVersionId = tempVer.Id;
                    }
                }

                List<Section__c> sectionsList = [Select Id, Name,Assessment_Template__c,
                Assessment_Template_Version__c,(Select Id,Name,Question__c,Assessment_Template__c,
                Assessment_Template_Version__c,Question_Type__c,Conditional_Response__c,
                HelpText__c,OptionValueSet__c,Parent_Question__c,
                Question_Sequence_Number__c,Required__c,Requires_File_Upload__c,
                Section__c FROM Questions__r) FROM Section__c WHERE Assessment_Template_Version__c = :versionId];

               
                List<Question__c> oldQuestionsList = new List<Question__c>();
                List<Question__c> questionsList = new List<Question__c>();
                for(Section__c section : sectionsList){
                    system.debug('section----->'+section);
                    Section__c newSection = section.clone(false, true); //do a deep clone
                    newSection.Assessment_Template_Version__c = newVersionId;
                    newSection.Cloned_Record_Id__c = section.Id;
                    newSectionsList.add(newSection);
                    oldQuestionsList.addAll(section.Questions__r);
                }
                Map<Id,Id> sectionIdsMap = new Map<Id,Id>();

                //insert sections
                insert newSectionsList;
                for(Section__c sec:newSectionsList){
                    sectionIdsMap.put(sec.Cloned_Record_Id__c,sec.Id);
                }
                system.debug('sectionIdsMap------->'+sectionIdsMap);
                for(Question__c question : oldQuestionsList){
                    Question__c newQuestion = question.clone(false, true);
                    newQuestion.Section__c = sectionIdsMap.get(question.Section__c);
                    newQuestion.Assessment_Template_Version__c = newVersionId;
                    questionsList.add(newQuestion);
                }
                insert questionsList;
                
                resultWrap.isSuccess = true;
                resultWrap.message = '';
                resultWrap.errorCode = '';
                
            }else{
                resultWrap.isSuccess = false;
                resultWrap.message = 'No Existing Template Version';
                resultWrap.errorCode = '';
            }
        }catch(Exception e){
            Database.rollback(sp);
            resultWrap.isSuccess = false;
            resultWrap.message = e.getMessage();
            resultWrap.errorCode = '';
        }
        return resultWrap;
    }
    public class ResultWrapper{
        @AuraEnabled public boolean isSuccess;
        @AuraEnabled public string message;
        @AuraEnabled public string errorCode;
    }
}