force-app/main/default/objects/Assessment_Template__c/Assessment_Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Template__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Inactive&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assessment_Template_Version__c/Assessment_Template_Version__c.object-meta.xml
<CustomObject>
    <label>Assessment Template Version</label>
    <nameField>
        <label>Assessment Template Version Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessment Template Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Template_Version__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Assessment Template Versions</relationshipLabel>
    <relationshipName>Assessment_Template_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Assessment_Template_Version__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template Version</label>
    <referenceTo>Assessment_Template_Version__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/OptionValueSet__c.field-meta.xml
<CustomField>
    <fullName>OptionValueSet__c</fullName>
    <label>Response Values</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence_Number__c</fullName>
    <label>Question Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Assessment_Template_Version__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template Version</label>
    <referenceTo>Assessment_Template_Version__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Cloned_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Cloned_Record_Id__c</fullName>
    <label>Cloned Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/No_of_Questions__c.field-meta.xml
<CustomField>
    <fullName>No_of_Questions__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No of Questions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Parent_Section__c.field-meta.xml
<CustomField>
    <fullName>Parent_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Section</label>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Root_Section__c.field-meta.xml
<CustomField>
    <fullName>Root_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Root Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Sections (Root Section)</relationshipLabel>
    <relationshipName>Sections1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Section__c/fields/Section_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Section_Sequence_Number__c</fullName>
    <label>Section Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssessmentTemplateController.cls
/* 
* Class Name        : AssessmentTemplateController
* Developer         : Priyanka         
* Created Date      : 
* Description       : AssessmentTemplateController class is used for SOQl on Question__c,Section__c,Assessment_Template__c and DML operations on the objects Sections,Questions.
* Last Modified Date: 23-06-2023
*/
public with sharing class AssessmentTemplateController {
    public static SecurityCheckController safe = new SecurityCheckController();//use singleton pattern
    
    //get Section Records for LookupField
    @AuraEnabled(cacheable=true)
    public static List<Section__c> getSections(String sectionName, string templateId) {
        List<Section__c> secList =new List<Section__c>();
        if(sectionName !='') {
            String secName ='%'+ sectionName +'%';
            secList =[select Id,Name from Section__c where Assessment_Template__c=:templateId AND Name LIKE :secName ];
        }
        else {
            secList =[select Id,Name from Section__c where Assessment_Template__c=:templateId ];
        }
        return secList; 
    }
    
    //Get Template Details
    @AuraEnabled(Cacheable=true)
    Public static Boolean getTemplateDetails(String templateId) {
        boolean hasStatusNew = false;
        try {
            
            if(templateId != null) {
                List<Assessment_Template__c> AssessmentList= [Select Status__c from Assessment_Template__c where ID=:templateId LIMIT 1];
                Assessment_Template__c assessmenttemp=(AssessmentList.size()==1)?AssessmentList[0]:null;
                if(assessmenttemp  !=null ) {
                    if(assessmenttemp.Status__c == 'New')
                        hasStatusNew = true;
                    else
                        hasStatusNew = false;
                }
            }
        }
        catch(Exception e) {
            System.debug('Exception e=='+e.getmessage()); 
        }
        return hasStatusNew;
    }
    
    /* getRecordsCount method is used to get the count of Records to particular Assessment Template */
    @AuraEnabled
    Public static Integer getRecordsCount(String templateId, String objName) {
        Integer totalRecsCount = 0;
        try {
            if(templateId!=null) {
                if(objName=='Sections') {
                    List<Section__c> sectionList=[select Id  from Section__c where Assessment_Template__c =: templateId ];
                    totalRecsCount=sectionList.size();
                }
                else if(objName=='Questions') {
                    List<Question__c> sectionList=[select Id  from Question__c where Assessment_Template__c =: templateId AND Section__c!=null];
                    totalRecsCount=sectionList.size();
                }
            }
        } 
        catch(Exception e) {
            System.debug('Exception e=='+e.getmessage());
        }
        return totalRecsCount;
    }
    
    
    /* getTemplateSections method is used to get all the Sections related to particular Assessment Template */
    @AuraEnabled
    Public static List<Section__c> getTemplateSections(String templateId) {
        try {
            if(templateId!=null) {
                String query = 'Select Id, Name,Section_Sequence_Number__c, Parent_Section__c, Root_Section__c, Assessment_Template__c, Assessment_Template_Version__c, No_of_Questions__c, Historical_Id__c, Cloned_Record_Id__c, Assessment_Template__r.Status__c,(select Id, Rhythm__Question__c, Section__c from Questions__r) from Section__c where Assessment_Template__c = \'' + templateId + '\' order by Section_Sequence_Number__c ASC';
                return safe.doQuery(query);
            } 
        }
        catch(Exception e) {
            System.debug('getTemplateSections Exception : '+e.getmessage());
        }
        return null;
    }
    
    /* getQuestionsLists method is used to get all the questions */
    @AuraEnabled
    Public static List<Question__c> getQuestionsLists(String templateId) {
        try {
            if(templateId!=null) {
                return [select Id, Rhythm__Question__c, Section__c from Question__c where Assessment_Template__c =:templateId AND Section__c!=null order by Question_Sequence_Number__c ASC];
            }
        }
        catch(Exception e) {
            System.debug('Exception e=='+e.getmessage());
        }
        return null;
    }
    
    
    /* getTemplateQuestionList method is used to get all the questions related to template */
    @AuraEnabled
    Public static List<Question__c> getTemplateQuestionList(String templateId, Integer recslimit) {
        try { 
            if(templateId!=null) {
                String query='Select Id, Name, Section__c,Question_Sequence_Number__c, OptionValueSet__c, Question_Type__c, Question__c, Assessment_Template__c, Section__r.Name, Rhythm__Assessment_Template__r.Rhythm__Status__c from Question__c where Assessment_Template__c = \'' + templateId + '\' AND Section__c!=null order by Section__r.Section_Sequence_Number__c ASC, Question_Sequence_Number__c ASC LIMIT '+recslimit;
                return safe.doQuery(query);
            }
        }
        catch(Exception e) {
            System.debug('Exception e=='+e.getmessage()); 
        }
        return null;
    }
    
    /* updateQustnRecords method is used to update section list */
    @AuraEnabled 
    public static void updateQustnRecords(list<Question__c> qstnList) {
        if(qstnList.size() > 0) {
            update qstnList;
        }
    }
    
    /* updateRecords method is used to update section list */
    @AuraEnabled
    public static void updateRecords(list<Section__c> secList) {
        if(secList.size() > 0) {
            update secList;
        }
    }
    
    /* deleteRecords method is used to delete the records */
    @AuraEnabled
    public static String deleteRecords(List<Id> recIdList, Boolean delchildobjrecs) {
        String status = 'Success';
        try {
            if(recIdList.size()>0) {
                Database.DeleteResult[] drchildList;
                if(delchildobjrecs==true) {
                    List<Question__c> questionList=[SELECT Id from Question__c where section__c IN:recIdList];
                    List<Question__c> subquestionList=[SELECT Id from Question__c where Id IN:recIdList];
                    if(questionList.size() > 0) {  
                       /* for(Question__c ques: subquestionList) {
                            if(recIdList.contains(ques.Id)) {
                                recIdList.remove(recIdList.indexof(ques.Id));
                            } 
                        }
                        if(subquestionList.size() > 0) {  
                            drchildList=safe.doDelete(subquestionList);
                        }*/
                        drchildList=safe.doDelete(questionList);
                    }
                }
                Database.DeleteResult[] drList=Database.delete(recIdList,true);
                for(Database.DeleteResult dr:drchildList) {
                    if(!dr.isSuccess()) {
                        for(Database.Error de:dr.getErrors()) {
                            status='Error Status Code: '+de.getStatusCode()+' || '+de.getMessage()+' || Error Source:'+de.getFields();
                        }
                    }
                }
            }
        }
        catch(Exception e) {
            System.debug('Exception e=='+e.getmessage());
        }
        return status;
    }
    
    //Get Questions Count
    @AuraEnabled
    public static Object questionsCount(Id sectionId)
    {
        List<AggregateResult> s=[select count(Id) q from Rhythm__Question__c where Rhythm__Section__c = :sectionId];
        return s[0].get('q');
    }
    
    //Get Sections Count
    @AuraEnabled
    public static Object sectionsCount(Id templateId)
    {
        List<AggregateResult> s=[select count(Id) s from Rhythm__Section__c where Assessment_Template__c = :templateId];
        return s[0].get('s');
    }
}