force-app/main/default/objects/Trigger_Configuration__mdt/Trigger_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Configuration</label>
    <pluralLabel>Trigger Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Field_Change_Handler__mdt/Trigger_Field_Change_Handler__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Field Change Handler</label>
    <pluralLabel>Trigger Field Change Handler</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_Field_Change_Handler__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <referenceTo>Trigger_Configuration__mdt</referenceTo>
    <relationshipLabel>Trigger Field Change Handler</relationshipLabel>
    <relationshipName>Trigger_Field_Change_Handler</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/TriggerFrameworkServiceController.cls
/**
* Class Name        : TriggerFrameworkServiceController
* Developer         : Sai Koushik Nimmaturi and Reethika Velpula           
* Created Date      : 
* @description      : It is used to get the record data dynamically
* Last Modified Date:  
*/
public with sharing class TriggerFrameworkServiceController {

     /**
    * @description To check the required criteria.
    * @param record new record data.
    * @param oldRecord Old record data.
    * @param objectName Name of the object.
    * @return
    */
    public boolean checkEntryCriteria(sObject record, sObject oldRecord, string objectName){
        boolean isCriteriaMet = false;
        string triggerObjId = Trigger_Configuration__mdt.getInstance(objectName).Id;
        List<string> fieldsList = getUpdatableFields(triggerObjId);
        if(fieldsList.isEmpty() == false){ 
            for(string fName:fieldsList){
                if(objectName.equalsIgnoreCase('Assessment_Template_c') && fName.equalsIgnoreCase('Status__c')){
                    if(string.valueOf(record.get(fName)).equalsIgnoreCase('New') && string.valueOf(oldRecord.get(fName)).equalsIgnoreCase('Active')){
                        isCriteriaMet = true;
                    }else if(string.valueOf(oldRecord.get(fName)).equalsIgnoreCase('Inactive')){
                        isCriteriaMet = true;
                    }
                }else{
                    if(record.get(fName) != oldRecord.get(fName)){
                        isCriteriaMet = true;
                    }
                }
            }
        }
        return isCriteriaMet;
    }
    
     /**
    * @description To get the fields to be updated.
    * @param triggerObjId object id.
    * @return
    */
    public List<string> getUpdatableFields(string triggerObjId){
        List<string> fieldsList = new List<string>();
        for(Trigger_Field_Change_Handler__mdt tfh:[select id, MasterLabel from Trigger_Field_Change_Handler__mdt where Object_Name__c =:triggerObjId]){
            fieldsList.add(tfh.MasterLabel);
        }
        return fieldsList;
    }
}