force-app/main/default/objects/AccountAssessmentRelation__c/AccountAssessmentRelation__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAssessmentRelation__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipName>AccountAssessmentRelation</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Supplier__c/Assessment_Supplier__c.object-meta.xml
<CustomObject>
    <label>Assessment Supplier</label>
    <nameField>
        <displayFormat>AS-{000000}</displayFormat>
        <label>Assessment Supplier Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Suppliers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Supplier__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Assessment Suppliers</relationshipLabel>
    <relationshipName>Assessment_Suppliers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment_Template__c/Assessment_Template__c.object-meta.xml
<CustomObject>
    <label>Template</label>
    <nameField>
        <label>Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Section</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Section__c.Assessment_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Assessment_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Section__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/Response__c.object-meta.xml
<CustomObject>
    <label>Response</label>
    <nameField>
        <label>Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response__c/fields/AccountAssessmentRelation__c.field-meta.xml
<CustomField>
    <fullName>AccountAssessmentRelation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountAssessmentRelation</label>
    <referenceTo>AccountAssessmentRelation__c</referenceTo>
    <relationshipLabel>Supplier Response</relationshipLabel>
    <relationshipName>Supplier_Response</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Responses</relationshipLabel>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Section__c/Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Section__c/fields/Assessment_Template__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Template__c</fullName>
    <label>Assessment Template</label>
    <referenceTo>Assessment_Template__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/* Class Name   : AssessmentController
* Developer         :  Sai Koushik Nimmaturi and Reethika Velpula      
* Created Date      :
* Description       : TestDataFactory class is used to create test data.
* Last Modified Date:
*/


public class TestDataFactory{
    /**
    * createRecords methods is used to create the records for all objects.
    * @param records This is a list of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */
    public static List<SObject> createRecords(List<SObject> records, Boolean doInsert, Map<String, Object> attributes){
        try{
            Integer i = 0;
            if(attributes != null){
                for (Integer j =0; j < records.size(); j ++) {
                    SObject record = records[j];
                    system.debug('attributes------->'+attributes);
                    for (String key : attributes.keySet()) {
                        Object value = attributes.get(key);
                        if (value instanceof List<Object>) {
                            Object obj = ((List<Object>) value).get(i);
                            if( obj instanceof SObject ){
                                Id sObjectId = ((SObject) obj).Id;
                                record.put( key,sObjectId );
                            }
                            else {
                                record.put(key,obj);
                            }
                        } else {
                            record.put(key, value);
                        }
                    }
                    i++;
                }
            }
            if (doInsert) {
                insert records;
                system.debug('records=====>'+records);
            }
        } catch(Exception e){
            system.debug('Exception while creating record: '+e.getMessage()+e.getLineNumber());
        }
        return records;
    }

    /**
    * createAccounts method is used to create account records.
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */

    public static List<Account> createAccounts(Integer numToInsert, Boolean doInsert, Map<String, Object> attributes){
        List<Account> accountsToInsert = new List<Account>();
        for(Integer i=0; i< numToInsert; i++){
            Account acc = new Account();
            accountsToInsert.add(acc);
        }
        return createRecords(accountsToInsert, doInsert, attributes);
    }
    /**
    * createContacts method is used to create Contacts records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */  
     
    public static List<Contact> createContacts(Integer numToInsert, Boolean doInsert, Map<String, Object> attributes){
    List<contact> contactsToInsert = new List<Contact>();
        for(Integer i=0; i< numToInsert; i++){
            Contact ct=new Contact();
            contactsToInsert.add(ct);
        }
        return createRecords(contactsToInsert, doInsert, attributes);
    }

    public static List<User> createUser(Integer numToInsert, Boolean doInsert, Map<String, Object> attributes){
        List<user> usersToInsert = new List<user>();
        for(Integer i=0; i< numToInsert; i++){
            user u=new user();
            usersToInsert.add(u);
        }
        return createRecords(usersToInsert, doInsert, attributes);
    }
    /**
    * createAssessmentTemp method is used to create AssessmentTemplate records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */  

    public static List<Assessment_Template__c> createAssessmentTemp(Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
        List<Assessment_Template__c> atemp = new List<Assessment_Template__c>();
        for(Integer i=0; i< numToInsert; i++){
        Assessment_Template__c at = new Assessment_Template__c();
        atemp.add(at);
        }
       return createRecords(atemp, true, attributes);
    }
/**
* createSection method is used to create Section records.
* @param numToInsert This is a number of records to insert.  
* @param doInsert This is boolean value whether to insert record or not.
* @param attributes This is a map which contain record data to insert.
*/
   
    public static List<Section__c> createSection(Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
        List<Section__c> secLst = new List<Section__c>();
        for(Integer i=0; i< numToInsert; i++){
        Section__c sec = new Section__c();
        secLst.add(sec);
        }
        return createRecords(secLst,true,attributes);
    }

    /**
    * createQuestion method is used to create Question records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */

    public static List<Question__c> createQuestion(Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
        List<Question__c> qlist = new List<Question__c>();
        for(Integer i=0; i< numToInsert; i++){
        Question__c q = new Question__c();
        qlist.add(q);
        }
        return createRecords(qlist,true,attributes);
    }
 
    /**
    * createAssessment method is used to create Assessment records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */  
    
    public static List<Assessment__c> createAssessment (Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
    List<Assessment__c> AssesmentList=new List<Assessment__c> ();
        for(Integer i=0; i< numToInsert; i++){
            Assessment__c at=new Assessment__c();
            AssesmentList.add(at);
        }
        return createRecords(AssesmentList,true,attributes);
    }

    /**
    * createResponse method is used to create Response records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */
   
    public static List<Response__c> createResponse(Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
        List<Response__c> resplist = new List<Response__c>();
        for(Integer i=0; i< numToInsert; i++){
        Response__c resp = new Response__c();
       
        resplist.add(resp);
        }
        return createRecords(resplist,true,attributes);
    }

    /**
    * createResponse method is used to create Response records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */
    public static List<AccountAssessmentRelation__c> createAccountAssessment(Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
        List<AccountAssessmentRelation__c> accountAssessmentlist = new List<AccountAssessmentRelation__c>();
        for(Integer i=0; i< numToInsert; i++){
        AccountAssessmentRelation__c accountAssessment = new AccountAssessmentRelation__c();
       
        accountAssessmentlist.add(accountAssessment);
        }
        return createRecords(accountAssessmentlist,true,attributes);
    }

    /**
    * createResponse method is used to create Response records
    * @param numToInsert This is a number of records to insert.  
    * @param doInsert This is boolean value whether to insert record or not.
    * @param attributes This is a map which contain record data to insert.
    */
    public static List<Assessment_Supplier__c> createSuppliers(Integer numToInsert, Boolean doInsert,Map<String, Object> attributes){
        List<Assessment_Supplier__c> supplierList = new List<Assessment_Supplier__c>();
        for(Integer i=0; i< numToInsert; i++){
            Assessment_Supplier__c accSupplier = new Assessment_Supplier__c();
            supplierList.add(accSupplier);
        }
        return createRecords(supplierList,true,attributes);
    }
}