force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/Action__c.object-meta.xml
<CustomObject>
    <label>Action Item</label>
    <nameField>
        <label>Action Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Action__c/fields/AccountAssessment__c.field-meta.xml
<CustomField>
    <fullName>AccountAssessment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountAssessment</label>
    <referenceTo>AccountAssessmentRelation__c</referenceTo>
    <relationshipLabel>Action Items</relationshipLabel>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Action_Item_Description__c.field-meta.xml
<CustomField>
    <fullName>Action_Item_Description__c</fullName>
    <label>Action Item Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/created__c.field-meta.xml
<CustomField>
    <fullName>created__c</fullName>
    <formula>CreatedBy.FirstName + CreatedBy.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>created</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Flag_Status__c.field-meta.xml
<CustomField>
    <fullName>Flag_Status__c</fullName>
    <formula>IF(

  TEXT(Status__c) == &apos;Closed&apos;,

  IMAGE(&apos;https://saas-customer-901-dev-ed--rhythm.scratch.vf.force.com/resource/1689524535000/Rhythm__GreenFlag&apos;,&apos;green&apos;,30,30),

  IMAGE(&apos;https://saas-customer-901-dev-ed--rhythm.scratch.vf.force.com/resource/1689524888000/Rhythm__RedFlag&apos;, &apos;red&apos;,30,30)

)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Flag Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Ownership__c.field-meta.xml
<CustomField>
    <fullName>Ownership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ownership</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/OwnershipName__c.field-meta.xml
<CustomField>
    <fullName>OwnershipName__c</fullName>
    <formula>Ownership__r.FirstName + &apos; &apos;+ Ownership__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OwnershipName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Related_module__c.field-meta.xml
<CustomField>
    <fullName>Related_module__c</fullName>
    <label>Related module</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assesments</fullName>
            </value>
            <value>
                <fullName>RFP</fullName>
            </value>
            <value>
                <fullName>Contracts</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Action__c/fields/Related_Record__c.field-meta.xml
<CustomField>
    <fullName>Related_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Record</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipName>Actions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Action__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Action Items</relationshipLabel>
    <relationshipName>Action_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <label>Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Review Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
                <isActive>false</isActive>
                <label>Closed</label>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CAPASelector.cls
public with sharing class CAPASelector {

    private static CAPASelector selector = null; //private static instance of the class
    /**
    * @description Singleton Design Pattern 
    * @return
    */
    public static CAPASelector getInstance(){
           if(selector == null){
                selector = new CAPASelector();
            }
        return selector;
    }

    /**
    * @description To get the action records related to particular user.
    * @param userName logged in user's username.
    * @return
    */
    public List<user> getRecordsList(string userName){
        return [SELECT Name from user WHERE Name LIKE : userName WITH SECURITY_ENFORCED];
    }

    /**
    * @description To get the action records related to a question and response record.
    * @param actionResponse Map with action related data.
    * @return
    */
    public List<Action__c> getActionResponse(Map<String,string> actionResponse){
        string questionId=actionResponse.get('Rhythm__Question__c');
        string accountAssessmentId=actionResponse.get('Rhythm__AccountAssessment__c');
        return [SELECT Name,Action_Item_Description__c,Due_Date__c,Supplier__c,Comments__c,Related_module__c,OwnershipName__c,
                Related_Record__c,Ownership__r.Name,Priority__c,Status__c,Ownership__c,Assigned_To__c,Assigned_To__r.Name
                FROM Action__c 
                WHERE Question__c=:questionId 
                AND AccountAssessment__c=:accountAssessmentId
                WITH SECURITY_ENFORCED];
        
    }

     /**
    * @description To get the action records related to a response record.
    * @param accountAssessment response data.
    * @return
    */
    public List<Action__c> getActionRecords(string accountAssessment){
        return [SELECT Question__c 
                FROM Action__c 
                WHERE AccountAssessment__c=:accountAssessment 
                WITH SECURITY_ENFORCED];
    }

     /**
    * @description To delete the action records related to a question and response record.
    * @param questionId question record id.
    * @param accountAssessmentId response record id.
    * @return
    */
    public List<Action__c> deleteActionData(string questionId,string accountAssessmentId){
        return  [SELECT Question__c,Assigned_To__c,Name 
                FROM Action__c 
                WHERE Question__c=:questionId 
                AND AccountAssessment__c=:accountAssessmentId
                WITH SECURITY_ENFORCED];
    }

     /**
    * @description To get the action records.
    * @return
    */
    public List<Action__c> actionRecords(){
        String userId = userinfo.getuserid();
        return [SELECT Name,Due_Date__c,Related_Record__c,Related_Record__r.Name,Ownership__r.Name,Status__c,OwnershipName__c,
                Priority__c,Assigned_To__r.Name,Flag_Status__c 
                FROM Action__c 
                WHERE Assigned_To__c=:userId
                WITH SECURITY_ENFORCED
               ORDER BY CreatedDate DESC];
    }

     /**
    * @description To get the selected action record.
    * @param actionid action record id.
    * @return
    */
    public List<Action__c> selectedActionRecord(string actionid){
        return [SELECT Name,Action_Item_Description__c,Due_Date__c,CreatedBy.Name,Flag_Status__c,Comments__c,
                Related_module__c,Related_Record__c,Related_Record__r.Name,Supplier__r.Name,OwnershipName__c,Priority__c,Status__c,created__c,
                Ownership__c,Ownership__r.Name,Assigned_To__c,Assigned_To__r.Name 
                FROM Action__c 
                WHERE Id=:actionid
                WITH SECURITY_ENFORCED];
    }

    /**
    * @description To delete the existing CAPA.
    * @param deletedata data needs to be deleted.
    */
    public List<Action__c> deleteCapa(List<String> questionId, String accountAssessmentid ){
        List<Action__c> lst=  [SELECT Question__c,Assigned_To__c,Name 
                                FROM Action__c 
                                WHERE Question__c IN : questionId
                                AND AccountAssessment__c=: accountAssessmentid
                                WITH SECURITY_ENFORCED];
         return lst;
    }

     /**
    * @description To notify the user for CAPA.
    * @return
    */
    public Object notifyUsers(){
        customNotificationType custom= [SELECT Id 
                                        FROM customNotificationType 
                                        WHERE DeveloperName = 'Action_Notification'
                                        WITH SECURITY_ENFORCED];
        return custom.Id;
    }

}