force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Conditional_Response__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Response__c</fullName>
    <label>Conditional Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Parent_Question__c.field-meta.xml
<CustomField>
    <fullName>Parent_Question__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Question</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Question_Sequence_Number__c</fullName>
    <label>Question Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionAttributeResponseService.cls
/**
* Class Name         : QuestionAttributeResponseService
* Developer          : Sai Koushik Nimmaturi, Sri Kushal Reddy N           
* Created Date       : 14-07-2023
* @description       : This class is used for building complex logic related to QuestionAttributeResponse functionalities
* Last Modified Date : 
*/
public with sharing class QuestionAttributeResponseService {
    public static SecurityCheckController safe = new SecurityCheckController();   //use singleton pattern
    private static Savepoint sp;
    @AuraEnabled	
	public static List<String> getQuestionTypeValues()
    {
        List<String> picklistvaluelst = new List<String>();
        Schema.DescribeFieldResult objFieldDescribe = Question__c.Question_Type__c.getDescribe();
		List<Schema.PicklistEntry> lstPickListValues = objFieldDescribe.getPickListValues();
		for (Schema.PicklistEntry objPickList : lstPickListValues) {
            picklistvaluelst.add(objPickList.getValue());
		}
        return picklistvaluelst;
    }
    @AuraEnabled
    public static List<SObject> createQuestions(List<SObject> questions, Boolean isUpdate)
    {
        System.debug('questions'+questions);
        if(isUpdate)
        {
            if(questions.isEmpty() == false){
                Database.SaveResult[] results = safe.doUpdate(questions);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
            //UPDATE questions;
        }
        else
        {
            if(questions.isEmpty() == false){
                Database.SaveResult[] results = safe.doInsert(questions);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
            //INSERT questions;
        }
        
        return questions;
    }
    @AuraEnabled
    public static List<SObject> createResponseAttributes(List<SObject> responseAttributes)
    {
        System.debug('responseAttributes'+responseAttributes);
        if(responseAttributes.isEmpty() == false){
                Database.SaveResult[] results = safe.doInsert(responseAttributes);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
        //return responseQuestionmap;
        //INSERT responseAttributes;
        return responseAttributes;
    }
     @AuraEnabled 
    public static List<SObject> createResponseQuestionMap(List<SObject> responseQuestionmap)
    {
        //INSERT responseQuestionmap;
        if(responseQuestionmap.isEmpty() == false){
                Database.SaveResult[] results = safe.doInsert(responseQuestionmap);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
        return responseQuestionmap;
    }
    @AuraEnabled  
    public static List<SObject> updateResponseAttributes(List<SObject> responseAttributes)
    {
        if(responseAttributes.isEmpty() == false){
                Database.SaveResult[] results = safe.doUpdate(responseAttributes);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
        //UPDATE responseAttributes;
        return responseAttributes;
    }
    @AuraEnabled
    public static List<Sobject> deleteResponseAttribute(String responseId)
    {
        List<Sobject> delrespAtr = QuestionAttributeResponseSelector.getQuestionResponseAttribute(responseId);
        System.debug('delrespAtr'+delrespAtr);
        if(delrespAtr.isEmpty() == false){
                    List<Database.DeleteResult> deleteResult = safe.doDelete(delrespAtr);
                    List<String> errorList = SecurityCheckController.safeClassExceptionHandlerDelete(deleteResult);
                    if(errorList.size()>0){
                        Database.rollback(sp);
                        throw new SecurityControllerException(String.join( errorList, ', ' ));
                    }
                }
        
        //DELETE delrespAtr;
        return delrespAtr;
    }
    public class SecurityControllerException extends Exception{
    }
    
    /**
    * @description Fetches the Question__c records based on search string and other parameters
    * @param parameterMap It is a stringified JSON of parameters required to fetch Question__c records
    * @return List of Question__c records
    */
    public static List<sObject> fetchQuestions(String parameterMap) {
        Map<String,Object> newParameterMap = (Map<String,Object>)JSON.deserializeUntyped(parameterMap);
        String assessmentId = (String)newParameterMap.get('assessmentId');
        String filter = ' WHERE Parent_Question__c = \'' + String.escapeSingleQuotes(assessmentId) + '\' ORDER BY Question_Sequence_Number__c ASC ';
        
        List<String> fields = new List<String>{'Id', 'Question__c', 'Conditional_Response__c', 'Question_Sequence_Number__c'};
        Map<String,Object> quesParameterMap = new Map<String,Object>{ 'fields'=>fields, 'filter'=>filter };
        return QuestionSelector.fetchQuestions(quesParameterMap);
    }
    
    /**
    * @description Updates the Child Questions with updated Sequence
    * @param parameterMap It is a stringified JSON of parameters required to update and fetch updated Question__c records
    * @return List of Question__c records
    */
    public static List<sObject> updateQuestionsSequence(String parameterMap) {
        Map<String,Object> newParameterMap = (Map<String,Object>)JSON.deserializeUntyped(parameterMap);
        return QuestionSelector.updateQuestionsSequence(newParameterMap);
    }
    
    @AuraEnabled
    public static List<SObject> deleteQuestion(String questionId,String templateId)
    {
        List<SObject> delQues = QuestionAttributeResponseSelector.getQuestionsData(questionId,templateId);
        //List<SObject> delRespAtr = QuestionAttributeResponseSelector.getResponseAttributes(questionId);
        List<SObject> delChildQues = QuestionAttributeResponseSelector.getChildQuestions(questionId,templateId);
        DELETE delQues;
        if(!delChildQues.isEmpty())
        {
            DELETE delChildQues;
        }
        /*if(!delRespAtr.isEmpty())
        {
            DELETE delRespAtr;
        }*/
        return delQues;
    }
    @AuraEnabled
    public static List<SObject> deleteQuesRespAttribute(String questionId)
    {
        List<SObject> delrespAtr = QuestionAttributeResponseSelector.getResponseAttributes(questionId);
        if(!delrespAtr.isEmpty())
        {
            DELETE delrespAtr;
        }
        return delrespAtr;
    }
}