force-app/main/default/objects/Question__c/Question__c.object-meta.xml
<CustomObject>
    <label>Question</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Question__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Formula</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Date/Time</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Picklist (Multi-Select)</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Text Area Text Area (Rich)</fullName>
            </value>
            <value>
                <fullName>Radio Select</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuestionService.cls
/** 
* Class Name        : QuestionSelector
* Developer         : Sai Koushik Nimmaturi      
* Created Date      : 
* @description      : QuestionService contains DML operations related to Question Object.
* Last Modified Date: 
*/
public class QuestionService {
	Public Static SecurityCheckController safe = new SecurityCheckController();//use singleton pattern
    private static Savepoint sp;
    Public class SecurityControllerException extends Exception{
    }
    /**
    * @description To get all the Response type field values.
    * @return 
    */
     @AuraEnabled	
	Public Static List<String> getQuestionTypeValues()
    {
        List<String> picklistvaluelst = new List<String>();
        Schema.DescribeFieldResult objFieldDescribe = Question__c.Question_Type__c.getDescribe();
		List<Schema.PicklistEntry> lstPickListValues = objFieldDescribe.getPickListValues();
		for (Schema.PicklistEntry objPickList : lstPickListValues) {
            picklistvaluelst.add(objPickList.getValue());
		}
        return picklistvaluelst;
    }
     /**
    * @description createQuestions methos is to create questions and update questions.
    * @param questions It is a Map of Question object contains fields.
    * @param isUpdate  is boolean value, if true updates the question, if false inserts the question.
    * @return Map of Id and its Question__c record
    */
    @AuraEnabled
    Public Static List<SObject> createQuestions(List<SObject> questions, Boolean isUpdate)
    {
        System.debug('questions'+questions);
        if(isUpdate)
        {
            if(questions.isEmpty() == false){
                Database.SaveResult[] results = safe.doUpdate(questions);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
            //UPDATE questions;
        }
        else
        {
            if(questions.isEmpty() == false){
                Database.SaveResult[] results = safe.doInsert(questions);
                List<String> errorsList = SecurityCheckController.safeClassExceptionHandlerInsert(results);
                system.debug('errorsList---->'+errorsList);
                if(errorsList.size()>0){
                    Database.rollback(sp);
                    throw new SecurityControllerException(String.join(errorsList, ', ' ));
                }
            }
            //INSERT questions;
        }
        
        return questions;
    }
    /**
    * @description createQuestions methos is to create questions and update questions.
    * @param questions It is a Map of Question object contains fields.
    * @param isUpdate  is boolean value, if true updates the question, if false inserts the question.
    * @return Map of Id and its Question__c record
    */
    @AuraEnabled
    Public Static List<SObject> deleteQuestion(String questionId,String templateId)
    {
        List<SObject> delQues = QuestionSelector.getQuestionsData(questionId,templateId);
        List<SObject> delChildQues = QuestionSelector.getChildQuestions(questionId,templateId);
        System.debug('delQues'+delQues);
        System.debug('delChildQues'+delChildQues);
        List<Database.DeleteResult> deleteResult = safe.doDelete(delQues);
                    List<String> errorList = SecurityCheckController.safeClassExceptionHandlerDelete(deleteResult);
                    if(errorList.size()>0){
                        Database.rollback(sp);
                        throw new SecurityControllerException(String.join( errorList, ', ' ));
                    }
        if(!delChildQues.isEmpty())
        {
           List<Database.DeleteResult> deletechildResult = safe.doDelete(delChildQues);
                    List<String> errorchildList = SecurityCheckController.safeClassExceptionHandlerDelete(deletechildResult);
                    if(errorchildList.size()>0){
                        Database.rollback(sp);
                        throw new SecurityControllerException(String.join( errorList, ', ' ));
                    }
        }
        return delQues;
    }
    /**
    * @description gets all questions data of particular template.
    * @param templateId It is an id of Template
    * @return List of Question__c records
    */
    Public Static List<SObject> getQuestions(String templateId){
        List<SObject> questionsLst = QuestionSelector.getQuestions(templateId);
        return questionsLst;
    }
    /**
    * @description gets conditional questions data of particular question.
    * @param templateId it is an id of Template
    * @param questionId it is an id of Question
    * @return List of Question__c record
    */
    Public Static List<SObject> getChildQuestions(String questionId,String templateId){
        List<SObject> questionsLst = QuestionSelector.getChildQuestions(questionId,templateId);
        return questionsLst;
    }
    
    /**
    * @description gets question data of particular question.
    * @param templateId it is an id of Template
    * @param questionId it is an id of Question
    * @return List of Question__c record
    */
    @AuraEnabled
    Public Static List<SObject> getQuestionsData(String questionId, String templateId){
        return QuestionSelector.getQuestionsData(questionId, templateId);
    }
}