force-app/main/default/objects/Response_Question_Map__c/Response_Question_Map__c.object-meta.xml
<CustomObject>
    <label>Response Question Map</label>
    <nameField>
        <displayFormat>RA-{000000}</displayFormat>
        <label>Response Question Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Question Maps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Response_Question_Map__c/fields/QuestionId__c.field-meta.xml
<CustomField>
    <fullName>QuestionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QuestionId</label>
    <referenceTo>Question__c</referenceTo>
    <relationshipLabel>Response Question Maps</relationshipLabel>
    <relationshipName>Response_Question_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Response_Question_Map__c/fields/ResponseAttributeId__c.field-meta.xml
<CustomField>
    <fullName>ResponseAttributeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ResponseAttributeId</label>
    <referenceTo>Response_Attribute__c</referenceTo>
    <relationshipLabel>Response Question Maps</relationshipLabel>
    <relationshipName>Response_Question_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResponseQuestionMapSelector.cls
/** 
* Class Name        : SectionSelector
* Developer         : Sai Koushik Nimmaturi and Reethika Velpula        
* Created Date      : 
* @description       : ResponseQuestionMapSelector contains queries related to ResponseMap Object.
* Last Modified Date: 
*/

public with sharing class ResponseQuestionMapSelector {
    @AuraEnabled
    public static List<Response_Question_Map__c> getResponeQmap(Map<Id,Id> raIdsMap){
        List<Response_Question_Map__c> resQmapList = [SELECT Id,QuestionId__c,ResponseAttributeId__c
                                                FROM Response_Question_Map__c
                                                WHERE ResponseAttributeId__c IN:raIdsMap.keySet()
                                                WITH SECURITY_ENFORCED];
        return resQmapList;
    }
}